version: 2
jobs:
  test:
    machine: true
    steps:
      - checkout
      - run: echo "ok"

workflows:
  version: 2
  test:
    jobs:
      - test

notify:
  webhooks:
    - url: https://samson.rdops.systems/integrations/circleci/00fda842a2d360df945321f71408db4e
