version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build
          command: docker build -t apinfo:${CIRCLE_TAG} .
  test:
    machine: true
    steps:
      - checkout
      - run: echo "ok"

workflows:
  version: 2
  build-n-test:
    jobs:
      - build
      - test

notify:
  webhooks:
    - url: https://samson.rdops.systems/integrations/circleci/00fda842a2d360df945321f71408db4e
