---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apinfo-app-server
  labels:
    project: apinfo
    role: app-server
spec:
  replicas: 3
  selector:
    matchLabels:
      project: apinfo
      role: app-server
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: apinfo-app-server
      labels:
        project: apinfo
        role: app-server
    spec:
      containers:
      - name: apinfo
        image: raittes/apinfo:latest
        resources:
          requests:
            cpu: 10m
            memory: 40Mi
          limits:
            cpu: 100m
            memory: 128Mi
        ports:
        - name: main-port
          containerPort: 4567
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 4567
          initialDelaySeconds: 5
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: apinfo
  labels:
    project: apinfo
    role: app-server
spec:
  type: NodePort
  ports:
  - port: 4567
    targetPort: main-port
  selector:
    project: apinfo
    role: app-server
